# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79f39e62233d0dffd8879db3bd08c677492ccc834ec8f3e907f4b0d3d5a7351c69b6f19422095e1fff8eeca549893ab5752fd4ee3e96d55f2bce26df91cfbff5

test:
  secret_key_base: 8c55ff9c38b3835ee6033c67f3a4011fae26366eaec1e0385287ef3e07d5fe6c5133ecf2a7a8d509d2d5eed122a80af95c3b31c56778cdd3e388f5a5570d90ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
